name: CI/CD Pipeline for Offline-Playground-Sandbox


on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: Development
    runs-on: ubuntu-latest
    steps:    
      - name: Add SSH private key to SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            
            cd /root/welwise-games/frontend/JS_SDK
            git pull origin main
